on: 
  push:
    branchs: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Merge release into main
        run: git merge main

      - uses: actions/setup-node@v3
        with: 
          node-version: 16.x
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build repository
        run: npm run build
      
      - name: Deploy output
        run: |
          git config user.name 'MaeDol'
          git config user.email 'rndka9@gmail.com'
          git add ./dist/* -f # gitignore 파일 때문에 무시되는 파일 -f 로 추가 
          git commit -m 'Github workflow build result'
          git push

