on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # 모든 브랜치를 가져오기 위해 0 으로 설정
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build repository
        run: npm run build

      - name: Configuring git
        run: |
          git config user.name 'MaetDol'
          git config user.email 'rndka9@gmail.com'

      - name: Deploy
        run: |
          git add ./dist/* -f # gitignore 때문에 무시되는 파일 -f 로 추가 
          git commit -m 'Deploy build output by Github workflow'
          git checkout release
          git merge main
          git push origin release

      - name: Move major tag
        run: |
          git tag -d v1
          git push --delete origin v1
          git tag v1
          git push --tag
